DROP DATABASE IF EXISTS systemservice ;
DROP USER IF EXISTS `system_service`@`%`;
CREATE DATABASE IF NOT EXISTS systemservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `system_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `systemservice`.* TO `system_service`@`%`;
FLUSH PRIVILEGES;